// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static void aCT_Save_New(IContext context, myfirstmodule.proxies.Order _order)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Order", _order == null ? null : _order.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Save_New").withParams(params).execute(context);
	}
	public static void edit_Customer(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.Edit_Customer").withParams(params).execute(context);
	}
	public static void edit_Driver(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.Edit_Driver").withParams(params).execute(context);
	}
	public static void edit_Order(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.Edit_Order").withParams(params).execute(context);
	}
	public static void edit_Trailer(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.Edit_Trailer").withParams(params).execute(context);
	}
	public static void print(IContext context, java.util.List<myfirstmodule.proxies.Order> _orderList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> listparam_orderList = null;
		if (_orderList != null)
		{
			listparam_orderList = new java.util.ArrayList<>();
			for (var obj : _orderList) {
				listparam_orderList.add(obj.getMendixObject());
			}
		}
		params.put("OrderList", listparam_orderList);

		Core.microflowCall("MyFirstModule.Print").withParams(params).execute(context);
	}
}
