// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Costomer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject costomerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Costomer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Debit_number("Debit_number"),
		Address("Address"),
		Location("Location"),
		Country("Country"),
		Costomer_Trailer("MyFirstModule.Costomer_Trailer"),
		Costomer_Driver("MyFirstModule.Costomer_Driver");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Costomer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Costomer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject costomerMendixObject)
	{
		if (costomerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, costomerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.costomerMendixObject = costomerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Costomer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Costomer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Costomer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Costomer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Costomer(context, mendixObject);
	}

	public static myfirstmodule.proxies.Costomer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Costomer.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Costomer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Costomer.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Debit_number
	 */
	public final java.lang.Long getDebit_number()
	{
		return getDebit_number(getContext());
	}

	/**
	 * @param context
	 * @return value of Debit_number
	 */
	public final java.lang.Long getDebit_number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Debit_number.toString());
	}

	/**
	 * Set value of Debit_number
	 * @param debit_number
	 */
	public final void setDebit_number(java.lang.Long debit_number)
	{
		setDebit_number(getContext(), debit_number);
	}

	/**
	 * Set value of Debit_number
	 * @param context
	 * @param debit_number
	 */
	public final void setDebit_number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long debit_number)
	{
		getMendixObject().setValue(context, MemberNames.Debit_number.toString(), debit_number);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of Location
	 */
	public final java.lang.String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final java.lang.String getLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(java.lang.String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Costomer_Trailer
	 */
	public final myfirstmodule.proxies.Trailer getCostomer_Trailer() throws com.mendix.core.CoreException
	{
		return getCostomer_Trailer(getContext());
	}

	/**
	 * @param context
	 * @return value of Costomer_Trailer
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Trailer getCostomer_Trailer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Trailer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Costomer_Trailer.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Trailer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Costomer_Trailer
	 * @param costomer_trailer
	 */
	public final void setCostomer_Trailer(myfirstmodule.proxies.Trailer costomer_trailer)
	{
		setCostomer_Trailer(getContext(), costomer_trailer);
	}

	/**
	 * Set value of Costomer_Trailer
	 * @param context
	 * @param costomer_trailer
	 */
	public final void setCostomer_Trailer(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Trailer costomer_trailer)
	{
		if (costomer_trailer == null) {
			getMendixObject().setValue(context, MemberNames.Costomer_Trailer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Costomer_Trailer.toString(), costomer_trailer.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Costomer_Driver
	 */
	public final myfirstmodule.proxies.Driver getCostomer_Driver() throws com.mendix.core.CoreException
	{
		return getCostomer_Driver(getContext());
	}

	/**
	 * @param context
	 * @return value of Costomer_Driver
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Driver getCostomer_Driver(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Driver result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Costomer_Driver.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Driver.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Costomer_Driver
	 * @param costomer_driver
	 */
	public final void setCostomer_Driver(myfirstmodule.proxies.Driver costomer_driver)
	{
		setCostomer_Driver(getContext(), costomer_driver);
	}

	/**
	 * Set value of Costomer_Driver
	 * @param context
	 * @param costomer_driver
	 */
	public final void setCostomer_Driver(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Driver costomer_driver)
	{
		if (costomer_driver == null) {
			getMendixObject().setValue(context, MemberNames.Costomer_Driver.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Costomer_Driver.toString(), costomer_driver.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return costomerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Costomer that = (myfirstmodule.proxies.Costomer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
