// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Order
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Order";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Createdate("Createdate"),
		Coupling_date("Coupling_date"),
		Status("Status"),
		Coupling_address("Coupling_address"),
		Destination_address("Destination_address"),
		Destination_date("Destination_date"),
		Info_Intern("Info_Intern"),
		Info_Extern("Info_Extern"),
		Order_Driver("MyFirstModule.Order_Driver"),
		Order_Costomer("MyFirstModule.Order_Costomer"),
		Order_Trailer("MyFirstModule.Order_Trailer"),
		Order_Truck("MyFirstModule.Order_Truck");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Order(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Order(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject)
	{
		if (orderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, orderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderMendixObject = orderMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Order.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Order initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Order.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Order initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Order(context, mendixObject);
	}

	public static myfirstmodule.proxies.Order load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Order.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Order> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Order.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Createdate
	 */
	public final java.util.Date getCreatedate()
	{
		return getCreatedate(getContext());
	}

	/**
	 * @param context
	 * @return value of Createdate
	 */
	public final java.util.Date getCreatedate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Createdate.toString());
	}

	/**
	 * Set value of Createdate
	 * @param createdate
	 */
	public final void setCreatedate(java.util.Date createdate)
	{
		setCreatedate(getContext(), createdate);
	}

	/**
	 * Set value of Createdate
	 * @param context
	 * @param createdate
	 */
	public final void setCreatedate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdate)
	{
		getMendixObject().setValue(context, MemberNames.Createdate.toString(), createdate);
	}

	/**
	 * @return value of Coupling_date
	 */
	public final java.util.Date getCoupling_date()
	{
		return getCoupling_date(getContext());
	}

	/**
	 * @param context
	 * @return value of Coupling_date
	 */
	public final java.util.Date getCoupling_date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Coupling_date.toString());
	}

	/**
	 * Set value of Coupling_date
	 * @param coupling_date
	 */
	public final void setCoupling_date(java.util.Date coupling_date)
	{
		setCoupling_date(getContext(), coupling_date);
	}

	/**
	 * Set value of Coupling_date
	 * @param context
	 * @param coupling_date
	 */
	public final void setCoupling_date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date coupling_date)
	{
		getMendixObject().setValue(context, MemberNames.Coupling_date.toString(), coupling_date);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final myfirstmodule.proxies.Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final myfirstmodule.proxies.Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(myfirstmodule.proxies.Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Status status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of Coupling_address
	 */
	public final java.lang.String getCoupling_address()
	{
		return getCoupling_address(getContext());
	}

	/**
	 * @param context
	 * @return value of Coupling_address
	 */
	public final java.lang.String getCoupling_address(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Coupling_address.toString());
	}

	/**
	 * Set value of Coupling_address
	 * @param coupling_address
	 */
	public final void setCoupling_address(java.lang.String coupling_address)
	{
		setCoupling_address(getContext(), coupling_address);
	}

	/**
	 * Set value of Coupling_address
	 * @param context
	 * @param coupling_address
	 */
	public final void setCoupling_address(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String coupling_address)
	{
		getMendixObject().setValue(context, MemberNames.Coupling_address.toString(), coupling_address);
	}

	/**
	 * @return value of Destination_address
	 */
	public final java.lang.String getDestination_address()
	{
		return getDestination_address(getContext());
	}

	/**
	 * @param context
	 * @return value of Destination_address
	 */
	public final java.lang.String getDestination_address(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Destination_address.toString());
	}

	/**
	 * Set value of Destination_address
	 * @param destination_address
	 */
	public final void setDestination_address(java.lang.String destination_address)
	{
		setDestination_address(getContext(), destination_address);
	}

	/**
	 * Set value of Destination_address
	 * @param context
	 * @param destination_address
	 */
	public final void setDestination_address(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String destination_address)
	{
		getMendixObject().setValue(context, MemberNames.Destination_address.toString(), destination_address);
	}

	/**
	 * @return value of Destination_date
	 */
	public final java.util.Date getDestination_date()
	{
		return getDestination_date(getContext());
	}

	/**
	 * @param context
	 * @return value of Destination_date
	 */
	public final java.util.Date getDestination_date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Destination_date.toString());
	}

	/**
	 * Set value of Destination_date
	 * @param destination_date
	 */
	public final void setDestination_date(java.util.Date destination_date)
	{
		setDestination_date(getContext(), destination_date);
	}

	/**
	 * Set value of Destination_date
	 * @param context
	 * @param destination_date
	 */
	public final void setDestination_date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date destination_date)
	{
		getMendixObject().setValue(context, MemberNames.Destination_date.toString(), destination_date);
	}

	/**
	 * @return value of Info_Intern
	 */
	public final java.lang.String getInfo_Intern()
	{
		return getInfo_Intern(getContext());
	}

	/**
	 * @param context
	 * @return value of Info_Intern
	 */
	public final java.lang.String getInfo_Intern(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Info_Intern.toString());
	}

	/**
	 * Set value of Info_Intern
	 * @param info_intern
	 */
	public final void setInfo_Intern(java.lang.String info_intern)
	{
		setInfo_Intern(getContext(), info_intern);
	}

	/**
	 * Set value of Info_Intern
	 * @param context
	 * @param info_intern
	 */
	public final void setInfo_Intern(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String info_intern)
	{
		getMendixObject().setValue(context, MemberNames.Info_Intern.toString(), info_intern);
	}

	/**
	 * @return value of Info_Extern
	 */
	public final java.lang.String getInfo_Extern()
	{
		return getInfo_Extern(getContext());
	}

	/**
	 * @param context
	 * @return value of Info_Extern
	 */
	public final java.lang.String getInfo_Extern(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Info_Extern.toString());
	}

	/**
	 * Set value of Info_Extern
	 * @param info_extern
	 */
	public final void setInfo_Extern(java.lang.String info_extern)
	{
		setInfo_Extern(getContext(), info_extern);
	}

	/**
	 * Set value of Info_Extern
	 * @param context
	 * @param info_extern
	 */
	public final void setInfo_Extern(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String info_extern)
	{
		getMendixObject().setValue(context, MemberNames.Info_Extern.toString(), info_extern);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_Driver
	 */
	public final myfirstmodule.proxies.Driver getOrder_Driver() throws com.mendix.core.CoreException
	{
		return getOrder_Driver(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Driver
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Driver getOrder_Driver(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Driver result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_Driver.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Driver.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_Driver
	 * @param order_driver
	 */
	public final void setOrder_Driver(myfirstmodule.proxies.Driver order_driver)
	{
		setOrder_Driver(getContext(), order_driver);
	}

	/**
	 * Set value of Order_Driver
	 * @param context
	 * @param order_driver
	 */
	public final void setOrder_Driver(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Driver order_driver)
	{
		if (order_driver == null) {
			getMendixObject().setValue(context, MemberNames.Order_Driver.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_Driver.toString(), order_driver.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_Costomer
	 */
	public final myfirstmodule.proxies.Costomer getOrder_Costomer() throws com.mendix.core.CoreException
	{
		return getOrder_Costomer(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Costomer
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Costomer getOrder_Costomer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Costomer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_Costomer.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Costomer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_Costomer
	 * @param order_costomer
	 */
	public final void setOrder_Costomer(myfirstmodule.proxies.Costomer order_costomer)
	{
		setOrder_Costomer(getContext(), order_costomer);
	}

	/**
	 * Set value of Order_Costomer
	 * @param context
	 * @param order_costomer
	 */
	public final void setOrder_Costomer(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Costomer order_costomer)
	{
		if (order_costomer == null) {
			getMendixObject().setValue(context, MemberNames.Order_Costomer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_Costomer.toString(), order_costomer.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_Trailer
	 */
	public final myfirstmodule.proxies.Trailer getOrder_Trailer() throws com.mendix.core.CoreException
	{
		return getOrder_Trailer(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Trailer
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Trailer getOrder_Trailer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Trailer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_Trailer.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Trailer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_Trailer
	 * @param order_trailer
	 */
	public final void setOrder_Trailer(myfirstmodule.proxies.Trailer order_trailer)
	{
		setOrder_Trailer(getContext(), order_trailer);
	}

	/**
	 * Set value of Order_Trailer
	 * @param context
	 * @param order_trailer
	 */
	public final void setOrder_Trailer(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Trailer order_trailer)
	{
		if (order_trailer == null) {
			getMendixObject().setValue(context, MemberNames.Order_Trailer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_Trailer.toString(), order_trailer.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_Truck
	 */
	public final myfirstmodule.proxies.Truck getOrder_Truck() throws com.mendix.core.CoreException
	{
		return getOrder_Truck(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Truck
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Truck getOrder_Truck(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Truck result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_Truck.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Truck.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_Truck
	 * @param order_truck
	 */
	public final void setOrder_Truck(myfirstmodule.proxies.Truck order_truck)
	{
		setOrder_Truck(getContext(), order_truck);
	}

	/**
	 * Set value of Order_Truck
	 * @param context
	 * @param order_truck
	 */
	public final void setOrder_Truck(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Truck order_truck)
	{
		if (order_truck == null) {
			getMendixObject().setValue(context, MemberNames.Order_Truck.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_Truck.toString(), order_truck.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Order that = (myfirstmodule.proxies.Order) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
