// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Trailer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject trailerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Trailer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Number("Number"),
		Trailer_type("Trailer_type"),
		ADR_trailer("ADR_trailer"),
		Cool_trailer("Cool_trailer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Trailer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Trailer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject trailerMendixObject)
	{
		if (trailerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, trailerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.trailerMendixObject = trailerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Trailer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Trailer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Trailer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Trailer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Trailer(context, mendixObject);
	}

	public static myfirstmodule.proxies.Trailer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Trailer.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Trailer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Trailer.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Long getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Long getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Long number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * Set value of Trailer_type
	 * @param trailer_type
	 */
	public final myfirstmodule.proxies.TrailerType getTrailer_type()
	{
		return getTrailer_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Trailer_type
	 */
	public final myfirstmodule.proxies.TrailerType getTrailer_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Trailer_type.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.TrailerType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Trailer_type
	 * @param trailer_type
	 */
	public final void setTrailer_type(myfirstmodule.proxies.TrailerType trailer_type)
	{
		setTrailer_type(getContext(), trailer_type);
	}

	/**
	 * Set value of Trailer_type
	 * @param context
	 * @param trailer_type
	 */
	public final void setTrailer_type(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.TrailerType trailer_type)
	{
		if (trailer_type != null) {
			getMendixObject().setValue(context, MemberNames.Trailer_type.toString(), trailer_type.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Trailer_type.toString(), null);
		}
	}

	/**
	 * Set value of ADR_trailer
	 * @param adr_trailer
	 */
	public final myfirstmodule.proxies.ADR_trailer getADR_trailer()
	{
		return getADR_trailer(getContext());
	}

	/**
	 * @param context
	 * @return value of ADR_trailer
	 */
	public final myfirstmodule.proxies.ADR_trailer getADR_trailer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ADR_trailer.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.ADR_trailer.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ADR_trailer
	 * @param adr_trailer
	 */
	public final void setADR_trailer(myfirstmodule.proxies.ADR_trailer adr_trailer)
	{
		setADR_trailer(getContext(), adr_trailer);
	}

	/**
	 * Set value of ADR_trailer
	 * @param context
	 * @param adr_trailer
	 */
	public final void setADR_trailer(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ADR_trailer adr_trailer)
	{
		if (adr_trailer != null) {
			getMendixObject().setValue(context, MemberNames.ADR_trailer.toString(), adr_trailer.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ADR_trailer.toString(), null);
		}
	}

	/**
	 * Set value of Cool_trailer
	 * @param cool_trailer
	 */
	public final myfirstmodule.proxies.Cool_trailer getCool_trailer()
	{
		return getCool_trailer(getContext());
	}

	/**
	 * @param context
	 * @return value of Cool_trailer
	 */
	public final myfirstmodule.proxies.Cool_trailer getCool_trailer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Cool_trailer.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Cool_trailer.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Cool_trailer
	 * @param cool_trailer
	 */
	public final void setCool_trailer(myfirstmodule.proxies.Cool_trailer cool_trailer)
	{
		setCool_trailer(getContext(), cool_trailer);
	}

	/**
	 * Set value of Cool_trailer
	 * @param context
	 * @param cool_trailer
	 */
	public final void setCool_trailer(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Cool_trailer cool_trailer)
	{
		if (cool_trailer != null) {
			getMendixObject().setValue(context, MemberNames.Cool_trailer.toString(), cool_trailer.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Cool_trailer.toString(), null);
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return trailerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Trailer that = (myfirstmodule.proxies.Trailer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
